### ISSUE TITLE
yamerl throws error if run from a mix task

### ISSUE THREAD

**Issue by bobbypriam** [KamilLelonek/yaml-elixir#14]
Hello, I'm having trouble using YamlElixir in my mix task. I have some data in a yaml format with the following form:

`priv/portals/foo.yml`
```yaml
# Display name for the portal.
name: Foo Portal

# Unique, lowercase, URL safe slug.
slug: fooportal

# Main site of this portal.
site_url: http://fooportal.com

# Hosts containing articles of this portal. May add more if necessary.
# Leave out the protocol (http/https).
hosts:
  - a.fooportal.com
  - b.fooportal.com
```

My mix task is as follows:

```elixir
defmodule Mix.Tasks.Mytask.Portal.Create do
  use Mix.Task

  def run(args) do
    case OptionParser.parse(args) do
      {_, [], _} ->
        Mix.raise "expected to receive the file name."
      {_, [name], _} ->
        path = Path.absname "priv/portals"
        file = Path.join path, "#{name}.yml"
        content = File.read! file
        IO.inspect content
        data = YamlElixir.read_from_string content
        IO.inspect data
    end
  end

end
```

When running `mix mytask.portal.create foo`, it successfully outputs the content of the file, but the YamlElixir line errors with the following message:

```
** (MatchError) no match of right hand side value: :undefined
    /path/to/my/project/deps/yamerl/src/yamerl_app.erl:67: :yamerl_app.get_param/1
    /path/to/my/project/deps/yamerl/src/yamerl_constr.erl:450: :yamerl_constr.setup_node_mods/1
    /path/to/my/project/deps/yamerl/src/yamerl_constr.erl:520: :yamerl_constr.initialize/1
    /path/to/my/project/deps/yamerl/src/yamerl_constr.erl:203: :yamerl_constr.string/2
    lib/yaml_elixir.ex:35: YamlElixir.read_from_string/2
    lib/mix/tasks/mytask.portal.create.ex:13: Mix.Tasks.Mytask.Portal.Create.run/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```

I've also tried substituting `YamlElixir.read_from_string` with `YamlElixir.read_from_file` directly to load the file, but still get the error. What's funny is that if I run it in `iex`, it functions just fine:

```elixir
$ iex -S mix
# some iex output
iex(1)> YamlElixir.read_from_file "priv/portals/foo.yml"
%{"hosts" => ["a.fooportal.com", "b.fooportal.com"], "name" => "Foo Portal",
  "site_url" => "http://fooportal.com", "slug" => "fooportal"}
```

If it helps, I'm using `yaml_elixir@1.2.1`. What could I be missing?
