### ISSUE TITLE
The CaseClauseError raise when yaml key is like to float

### ISSUE THREAD

**Issue by nazipov** [KamilLelonek/yaml-elixir#5]
When I try to read yaml file [caps_device_type.yaml](https://github.com/commenthol/ua-parser-caps/blob/master/caps_device_type.yaml), wich contains the following lines:

``` yaml
...
        8800e-1:
          capabilities:
            info:
              date: 2007-12
              marketing_name: Nokia 8800 Arte
...
```

I get the error:

``` elixir
iex(1)> File.cwd! |> Path.join("caps_device_type.yaml") |> YamlElixir.read_from_file
** (CaseClauseError) no case clause matching: {:yamerl_float, :yamerl_node_float, 'tag:yaml.org,2002:float', [line: 47223, column: 9], 880.0}
    (yaml_elixir) lib/yaml_elixir/mapper.ex:35: YamlElixir.Mapper._tuples_to_map/2
    (yaml_elixir) lib/yaml_elixir/mapper.ex:37: YamlElixir.Mapper._tuples_to_map/2
         (elixir) lib/enum.ex:1088: Enum."-map/2-lists^map/1-0-"/2
    (yaml_elixir) lib/yaml_elixir/mapper.ex:6: YamlElixir.Mapper.process/1
```
