### ISSUE TITLE
`atoms: true` not working for `read_from_file/2`

### ISSUE THREAD

**Issue by zastrixarundell** [KamilLelonek/yaml-elixir#58]
Given this YML file:

```yaml
machines:
  Z390D:
    mac: 18:c0:4d:33:b9:a9
    broadcast: 10.17.17.1
  Darwin:
    mac: 50:e5:49:d2:47:bc
    broadcast: 10.17.17.1
  Another:
    mac: 21:21:21:21:21:21
    broadcast: 10.17.17.1
```

And running the following code:

```elixir
    @configuration
    |> Keyword.get(:config_location, "/etc/wolab/machines.yml")
    |> YamlElixir.read_from_file(atoms: true)
    |> IO.inspect()
```

I get this as my output:

```elixir
{:ok,
 %{
   "machines" => %{
     "Another" => %{"broadcast" => "10.17.17.1", "mac" => "21:21:21:21:21:21"},
     "Darwin" => %{"broadcast" => "10.17.17.1", "mac" => "50:e5:49:d2:47:bc"},
     "Z390D" => %{"broadcast" => "10.17.17.1", "mac" => "18:c0:4d:33:b9:a9"}
   }
 }}
 ```
